language: cpp

os: osx
osx_image: xcode10.2

addons:
  homebrew:
    packages:
      - meson
      - qt

script:
  - export PATH="/usr/local/opt/qt/bin:$PATH"
  - meson builddir
  - ninja -C builddir

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MHozbnR1JTNBbWF0cml4Lm9yZy8lMjF5akJlQnpZSGtQbnRpc2xwSmYlM0FtYXRyaXgub3Jn"
        on_success: never
        on_failure: always
        on_start: never
